# Changes here will be overwritten by Copier
_commit: v1.0.0
_src_path: https://github.com/worldworm/copier-base-copier.git
answersfile_suffix: poetry-meta
child_template_name: copier-poetry
child_template_url: https://github.com/worldworm/copier-poetry
copyright_license: MIT
copyright_year_start: 2023
copyright_year_today: 2023
is_meta: true
need_trust: false
project_description: Copier meta template for poetry projects.
project_emoji: 📋
project_name: copier-poetry-meta
ref_tech_url: https://github.com/python-poetry/poetry
repository_name: copier-poetry-meta
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-poetry-meta
repository_username: worldworm
warning_early_dev: false

